graph LR;

Environment_variables["Environment variables"];
PROJECT_ROOT["PROJECT_ROOT"];
Environment_variables --> PROJECT_ROOT;
Algunas_cosas_se_deben_poner_simbolos["Algunas cosas. se deben poner símbolos"];
PROJECT_ROOT --> Algunas_cosas_se_deben_poner_simbolos;
NODE_ENV["NODE_ENV"];
Environment_variables --> NODE_ENV;
Algunas_cosas_se_deben_poner_mas_simbolos["Algunas cosas. se deben poner más símbolos"];
NODE_ENV --> Algunas_cosas_se_deben_poner_mas_simbolos;
SCHEMA_DB_USER["SCHEMA_DB_USER"];
Environment_variables --> SCHEMA_DB_USER;
SCHEMA_DB_USER_determines["SCHEMA_DB_USER determines..."];
SCHEMA_DB_USER --> SCHEMA_DB_USER_determines;
SCHEMA_DB_PASSWORD["SCHEMA_DB_PASSWORD"];
Environment_variables --> SCHEMA_DB_PASSWORD;
SCHEMA_DB_PASSWORD_determines["SCHEMA_DB_PASSWORD determines..."];
SCHEMA_DB_PASSWORD --> SCHEMA_DB_PASSWORD_determines;
SCHEMA_DB_HOST["SCHEMA_DB_HOST"];
Environment_variables --> SCHEMA_DB_HOST;
SCHEMA_DB_HOST_determines["SCHEMA_DB_HOST determines..."];
SCHEMA_DB_HOST --> SCHEMA_DB_HOST_determines;
SCHEMA_DB_PORT["SCHEMA_DB_PORT"];
Environment_variables --> SCHEMA_DB_PORT;
SCHEMA_DB_PORT_determines["SCHEMA_DB_PORT determines..."];
SCHEMA_DB_PORT --> SCHEMA_DB_PORT_determines;
SCHEMA_DB_NAME["SCHEMA_DB_NAME"];
Environment_variables --> SCHEMA_DB_NAME;
SCHEMA_DB_NAME_determines["SCHEMA_DB_NAME determines..."];
SCHEMA_DB_NAME --> SCHEMA_DB_NAME_determines;
SCHEMA_CONFIGURATIONS["SCHEMA_CONFIGURATIONS"];
Environment_variables --> SCHEMA_CONFIGURATIONS;
SCHEMA_CONFIGURATIONS_determines["SCHEMA_CONFIGURATIONS determines..."];
SCHEMA_CONFIGURATIONS --> SCHEMA_CONFIGURATIONS_determines;
SCHEMA_EXTENSIONS["SCHEMA_EXTENSIONS"];
Environment_variables --> SCHEMA_EXTENSIONS;
SCHEMA_EXTENSIONS_determines["SCHEMA_EXTENSIONS determines..."];
SCHEMA_EXTENSIONS --> SCHEMA_EXTENSIONS_determines;
SCHEMA_AS_JSON["SCHEMA_AS_JSON"];
Environment_variables --> SCHEMA_AS_JSON;
SCHEMA_AS_JSON_determines["SCHEMA_AS_JSON determines..."];
SCHEMA_AS_JSON --> SCHEMA_AS_JSON_determines;
SCHEMA_OUTPUT["SCHEMA_OUTPUT"];
Environment_variables --> SCHEMA_OUTPUT;
SCHEMA_OUTPUT_determines["SCHEMA_OUTPUT determines..."];
SCHEMA_OUTPUT --> SCHEMA_OUTPUT_determines;
SCHEMA_VIRTUAL_OUTPUT["SCHEMA_VIRTUAL_OUTPUT"];
Environment_variables --> SCHEMA_VIRTUAL_OUTPUT;
SCHEMA_VIRTUAL_OUTPUT_determines["SCHEMA_VIRTUAL_OUTPUT determines..."];
SCHEMA_VIRTUAL_OUTPUT --> SCHEMA_VIRTUAL_OUTPUT_determines;
DEBUG_SQL["DEBUG_SQL"];
Environment_variables --> DEBUG_SQL;
DEBUG_SQL_determines["DEBUG_SQL determines..."];
DEBUG_SQL --> DEBUG_SQL_determines;
DEBUG_TRACES["DEBUG_TRACES"];
Environment_variables --> DEBUG_TRACES;
DEBUG_TRACES_determines["DEBUG_TRACES determines..."];
DEBUG_TRACES --> DEBUG_TRACES_determines;
DEBUG_ERRORS["DEBUG_ERRORS"];
Environment_variables --> DEBUG_ERRORS;
DEBUG_ERRORS_determines["DEBUG_ERRORS determines..."];
DEBUG_ERRORS --> DEBUG_ERRORS_determines;
REST_DB_USER["REST_DB_USER"];
Environment_variables --> REST_DB_USER;
REST_DB_USER_determines["REST_DB_USER determines..."];
REST_DB_USER --> REST_DB_USER_determines;
REST_DB_PASSWORD["REST_DB_PASSWORD"];
Environment_variables --> REST_DB_PASSWORD;
REST_DB_PASSWORD_determines["REST_DB_PASSWORD determines..."];
REST_DB_PASSWORD --> REST_DB_PASSWORD_determines;
REST_DB_HOST["REST_DB_HOST"];
Environment_variables --> REST_DB_HOST;
REST_DB_HOST_determines["REST_DB_HOST determines..."];
REST_DB_HOST --> REST_DB_HOST_determines;
REST_DB_PORT["REST_DB_PORT"];
Environment_variables --> REST_DB_PORT;
REST_DB_PORT_determines["REST_DB_PORT determines..."];
REST_DB_PORT --> REST_DB_PORT_determines;
REST_DB_NAME["REST_DB_NAME"];
Environment_variables --> REST_DB_NAME;
REST_DB_NAME_determines["REST_DB_NAME determines..."];
REST_DB_NAME --> REST_DB_NAME_determines;
AUTH_DB_USER["AUTH_DB_USER"];
Environment_variables --> AUTH_DB_USER;
AUTH_DB_USER_determines["AUTH_DB_USER determines..."];
AUTH_DB_USER --> AUTH_DB_USER_determines;
AUTH_DB_PASSWORD["AUTH_DB_PASSWORD"];
Environment_variables --> AUTH_DB_PASSWORD;
AUTH_DB_PASSWORD_determines["AUTH_DB_PASSWORD determines..."];
AUTH_DB_PASSWORD --> AUTH_DB_PASSWORD_determines;
AUTH_DB_NAME["AUTH_DB_NAME"];
Environment_variables --> AUTH_DB_NAME;
AUTH_DB_NAME_determines["AUTH_DB_NAME determines..."];
AUTH_DB_NAME --> AUTH_DB_NAME_determines;
AUTH_DB_HOST["AUTH_DB_HOST"];
Environment_variables --> AUTH_DB_HOST;
AUTH_DB_HOST_determines["AUTH_DB_HOST determines..."];
AUTH_DB_HOST --> AUTH_DB_HOST_determines;
AUTH_DB_PORT["AUTH_DB_PORT"];
Environment_variables --> AUTH_DB_PORT;
AUTH_DB_PORT_determines["AUTH_DB_PORT determines..."];
AUTH_DB_PORT --> AUTH_DB_PORT_determines;
HISTORY_DB_USER["HISTORY_DB_USER"];
Environment_variables --> HISTORY_DB_USER;
HISTORY_DB_USER_determines["HISTORY_DB_USER determines..."];
HISTORY_DB_USER --> HISTORY_DB_USER_determines;
HISTORY_DB_PASSWORD["HISTORY_DB_PASSWORD"];
Environment_variables --> HISTORY_DB_PASSWORD;
HISTORY_DB_PASSWORD_determines["HISTORY_DB_PASSWORD determines..."];
HISTORY_DB_PASSWORD --> HISTORY_DB_PASSWORD_determines;
HISTORY_DB_NAME["HISTORY_DB_NAME"];
Environment_variables --> HISTORY_DB_NAME;
HISTORY_DB_NAME_determines["HISTORY_DB_NAME determines..."];
HISTORY_DB_NAME --> HISTORY_DB_NAME_determines;
HISTORY_DB_HOST["HISTORY_DB_HOST"];
Environment_variables --> HISTORY_DB_HOST;
HISTORY_DB_HOST_determines["HISTORY_DB_HOST determines..."];
HISTORY_DB_HOST --> HISTORY_DB_HOST_determines;
HISTORY_DB_PORT["HISTORY_DB_PORT"];
Environment_variables --> HISTORY_DB_PORT;
HISTORY_DB_PORT_determines["HISTORY_DB_PORT determines..."];
HISTORY_DB_PORT --> HISTORY_DB_PORT_determines;
STORAGE_INSTANCE["STORAGE_INSTANCE"];
Environment_variables --> STORAGE_INSTANCE;
STORAGE_INSTANCE_determines["STORAGE_INSTANCE determines..."];
STORAGE_INSTANCE --> STORAGE_INSTANCE_determines;
APP_URL["APP_URL"];
Environment_variables --> APP_URL;
APP_URL_determines["APP_URL determines..."];
APP_URL --> APP_URL_determines;
APP_PORT["APP_PORT"];
Environment_variables --> APP_PORT;
APP_PORT_determines["APP_PORT determines..."];
APP_PORT --> APP_PORT_determines;
EMAIL_USER["EMAIL_USER"];
Environment_variables --> EMAIL_USER;
EMAIL_USER_determines["EMAIL_USER determines..."];
EMAIL_USER --> EMAIL_USER_determines;
EMAIL_PASSWORD["EMAIL_PASSWORD"];
Environment_variables --> EMAIL_PASSWORD;
EMAIL_PASSWORD_determines["EMAIL_PASSWORD determines..."];
EMAIL_PASSWORD --> EMAIL_PASSWORD_determines;
