drop table if exists combo_user_and_group;
drop table if exists combo_user_and_permission;
drop table if exists combo_group_and_permission;
drop table if exists unconfirmed_users;
drop table if exists configuration;
drop table if exists sessions;
drop table if exists users;
drop table if exists groups;
drop table if exists permissions;