graph TD;

Plantomium_API["Plantomium API"];
REST_API["REST API"];
Plantomium_API --> REST_API;
srcrest["src/rest"];
REST_API --> srcrest;
Authentication_API["Authentication API"];
Plantomium_API --> Authentication_API;
srcauth["src/auth"];
Authentication_API --> srcauth;
Authorization_API["Authorization API"];
Plantomium_API --> Authorization_API;
srcauth["src/auth"];
Authorization_API --> srcauth;
History_API["History API"];
Plantomium_API --> History_API;
srchistory["src/history"];
History_API --> srchistory;
Store_API["Store API"];
Plantomium_API --> Store_API;
srcstore["src/store"];
Store_API --> srcstore;
Email_API["Email API"];
Plantomium_API --> Email_API;
srcemail["src/email"];
Email_API --> srcemail;
Router_API["Router API"];
Plantomium_API --> Router_API;
srcrouter["src/router"];
Router_API --> srcrouter;
Utils_API["Utils API"];
Plantomium_API --> Utils_API;
srcutils["src/utils"];
Utils_API --> srcutils;
Deploy_API["Deploy API"];
Plantomium_API --> Deploy_API;
srcdeploy["src/deploy"];
Deploy_API --> srcdeploy;
Config_API["Config API"];
Plantomium_API --> Config_API;
srcconfig["src/config"];
Config_API --> srcconfig;
Control_API["Control API"];
Plantomium_API --> Control_API;
srccontrol["src/control"];
Control_API --> srccontrol;
UI_API["UI API"];
Plantomium_API --> UI_API;
srcui["src/ui"];
UI_API --> srcui;
Docs_API["Docs API"];
Plantomium_API --> Docs_API;
docs["docs"];
Docs_API --> docs;
